// Mocks generated by Mockito 5.4.6 from annotations
// in keda/test/providers_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;

import 'package:keda/models/category.dart' as _i2;
import 'package:keda/models/expense.dart' as _i4;
import 'package:keda/models/finance_account.dart' as _i3;
import 'package:keda/models/monthly_summary.dart' as _i5;
import 'package:keda/repositories/api_client.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeCategory_0 extends _i1.SmartFake implements _i2.Category {
  _FakeCategory_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFinanceAccount_1 extends _i1.SmartFake
    implements _i3.FinanceAccount {
  _FakeFinanceAccount_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeExpense_2 extends _i1.SmartFake implements _i4.Expense {
  _FakeExpense_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMonthlySummary_3 extends _i1.SmartFake
    implements _i5.MonthlySummary {
  _FakeMonthlySummary_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSyncResponse_4 extends _i1.SmartFake implements _i6.SyncResponse {
  _FakeSyncResponse_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiClient extends _i1.Mock implements _i6.ApiClient {
  @override
  String get baseUrl =>
      (super.noSuchMethod(
            Invocation.getter(#baseUrl),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#baseUrl),
            ),
            returnValueForMissingStub: _i7.dummyValue<String>(
              this,
              Invocation.getter(#baseUrl),
            ),
          )
          as String);

  @override
  _i8.Future<List<_i2.Category>> getCategories() =>
      (super.noSuchMethod(
            Invocation.method(#getCategories, []),
            returnValue: _i8.Future<List<_i2.Category>>.value(<_i2.Category>[]),
            returnValueForMissingStub: _i8.Future<List<_i2.Category>>.value(
              <_i2.Category>[],
            ),
          )
          as _i8.Future<List<_i2.Category>>);

  @override
  _i8.Future<_i2.Category> createCategory(_i2.Category? category) =>
      (super.noSuchMethod(
            Invocation.method(#createCategory, [category]),
            returnValue: _i8.Future<_i2.Category>.value(
              _FakeCategory_0(
                this,
                Invocation.method(#createCategory, [category]),
              ),
            ),
            returnValueForMissingStub: _i8.Future<_i2.Category>.value(
              _FakeCategory_0(
                this,
                Invocation.method(#createCategory, [category]),
              ),
            ),
          )
          as _i8.Future<_i2.Category>);

  @override
  _i8.Future<_i2.Category> updateCategory(String? id, _i2.Category? category) =>
      (super.noSuchMethod(
            Invocation.method(#updateCategory, [id, category]),
            returnValue: _i8.Future<_i2.Category>.value(
              _FakeCategory_0(
                this,
                Invocation.method(#updateCategory, [id, category]),
              ),
            ),
            returnValueForMissingStub: _i8.Future<_i2.Category>.value(
              _FakeCategory_0(
                this,
                Invocation.method(#updateCategory, [id, category]),
              ),
            ),
          )
          as _i8.Future<_i2.Category>);

  @override
  _i8.Future<void> deleteCategory(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteCategory, [id]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<List<_i3.FinanceAccount>> getAccounts() =>
      (super.noSuchMethod(
            Invocation.method(#getAccounts, []),
            returnValue: _i8.Future<List<_i3.FinanceAccount>>.value(
              <_i3.FinanceAccount>[],
            ),
            returnValueForMissingStub:
                _i8.Future<List<_i3.FinanceAccount>>.value(
                  <_i3.FinanceAccount>[],
                ),
          )
          as _i8.Future<List<_i3.FinanceAccount>>);

  @override
  _i8.Future<_i3.FinanceAccount> createAccount(_i3.FinanceAccount? account) =>
      (super.noSuchMethod(
            Invocation.method(#createAccount, [account]),
            returnValue: _i8.Future<_i3.FinanceAccount>.value(
              _FakeFinanceAccount_1(
                this,
                Invocation.method(#createAccount, [account]),
              ),
            ),
            returnValueForMissingStub: _i8.Future<_i3.FinanceAccount>.value(
              _FakeFinanceAccount_1(
                this,
                Invocation.method(#createAccount, [account]),
              ),
            ),
          )
          as _i8.Future<_i3.FinanceAccount>);

  @override
  _i8.Future<_i3.FinanceAccount> updateAccount(
    String? id,
    _i3.FinanceAccount? account,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateAccount, [id, account]),
            returnValue: _i8.Future<_i3.FinanceAccount>.value(
              _FakeFinanceAccount_1(
                this,
                Invocation.method(#updateAccount, [id, account]),
              ),
            ),
            returnValueForMissingStub: _i8.Future<_i3.FinanceAccount>.value(
              _FakeFinanceAccount_1(
                this,
                Invocation.method(#updateAccount, [id, account]),
              ),
            ),
          )
          as _i8.Future<_i3.FinanceAccount>);

  @override
  _i8.Future<void> deleteAccount(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteAccount, [id]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<List<_i4.Expense>> getTransactions({String? month}) =>
      (super.noSuchMethod(
            Invocation.method(#getTransactions, [], {#month: month}),
            returnValue: _i8.Future<List<_i4.Expense>>.value(<_i4.Expense>[]),
            returnValueForMissingStub: _i8.Future<List<_i4.Expense>>.value(
              <_i4.Expense>[],
            ),
          )
          as _i8.Future<List<_i4.Expense>>);

  @override
  _i8.Future<_i4.Expense> createTransaction(_i4.Expense? expense) =>
      (super.noSuchMethod(
            Invocation.method(#createTransaction, [expense]),
            returnValue: _i8.Future<_i4.Expense>.value(
              _FakeExpense_2(
                this,
                Invocation.method(#createTransaction, [expense]),
              ),
            ),
            returnValueForMissingStub: _i8.Future<_i4.Expense>.value(
              _FakeExpense_2(
                this,
                Invocation.method(#createTransaction, [expense]),
              ),
            ),
          )
          as _i8.Future<_i4.Expense>);

  @override
  _i8.Future<_i4.Expense> updateTransaction(String? id, _i4.Expense? expense) =>
      (super.noSuchMethod(
            Invocation.method(#updateTransaction, [id, expense]),
            returnValue: _i8.Future<_i4.Expense>.value(
              _FakeExpense_2(
                this,
                Invocation.method(#updateTransaction, [id, expense]),
              ),
            ),
            returnValueForMissingStub: _i8.Future<_i4.Expense>.value(
              _FakeExpense_2(
                this,
                Invocation.method(#updateTransaction, [id, expense]),
              ),
            ),
          )
          as _i8.Future<_i4.Expense>);

  @override
  _i8.Future<void> deleteTransaction(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTransaction, [id]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<List<String>> getSuggestedNotes(String? categoryId) =>
      (super.noSuchMethod(
            Invocation.method(#getSuggestedNotes, [categoryId]),
            returnValue: _i8.Future<List<String>>.value(<String>[]),
            returnValueForMissingStub: _i8.Future<List<String>>.value(
              <String>[],
            ),
          )
          as _i8.Future<List<String>>);

  @override
  _i8.Future<_i5.MonthlySummary> getMonthlySummary(String? month) =>
      (super.noSuchMethod(
            Invocation.method(#getMonthlySummary, [month]),
            returnValue: _i8.Future<_i5.MonthlySummary>.value(
              _FakeMonthlySummary_3(
                this,
                Invocation.method(#getMonthlySummary, [month]),
              ),
            ),
            returnValueForMissingStub: _i8.Future<_i5.MonthlySummary>.value(
              _FakeMonthlySummary_3(
                this,
                Invocation.method(#getMonthlySummary, [month]),
              ),
            ),
          )
          as _i8.Future<_i5.MonthlySummary>);

  @override
  _i8.Future<void> createInvitation(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#createInvitation, [email]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<List<Map<String, dynamic>>> getMembers() =>
      (super.noSuchMethod(
            Invocation.method(#getMembers, []),
            returnValue: _i8.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
            returnValueForMissingStub:
                _i8.Future<List<Map<String, dynamic>>>.value(
                  <Map<String, dynamic>>[],
                ),
          )
          as _i8.Future<List<Map<String, dynamic>>>);

  @override
  _i8.Future<void> removeMember(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#removeMember, [userId]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<_i6.SyncResponse> sync({String? month}) =>
      (super.noSuchMethod(
            Invocation.method(#sync, [], {#month: month}),
            returnValue: _i8.Future<_i6.SyncResponse>.value(
              _FakeSyncResponse_4(
                this,
                Invocation.method(#sync, [], {#month: month}),
              ),
            ),
            returnValueForMissingStub: _i8.Future<_i6.SyncResponse>.value(
              _FakeSyncResponse_4(
                this,
                Invocation.method(#sync, [], {#month: month}),
              ),
            ),
          )
          as _i8.Future<_i6.SyncResponse>);

  @override
  _i8.Future<String> getServerVersion() =>
      (super.noSuchMethod(
            Invocation.method(#getServerVersion, []),
            returnValue: _i8.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#getServerVersion, []),
              ),
            ),
            returnValueForMissingStub: _i8.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#getServerVersion, []),
              ),
            ),
          )
          as _i8.Future<String>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}
