window.FF_CONFIG = {
  "API_URL": "API_URL_PLACEHOLD",
  "GOOGLE_CLIENT_ID": "GOOGLE_CLIENT_ID_PLACEHOLD",
  "TEST_MODE": "TEST_MODE_PLACEHOLD",
  "TEST_HOUSEHOLD_ID": "TEST_HOUSEHOLD_ID_PLACEHOLD"
};
